### PR TITLE
Add EST120 QP & HUN102 Question bank

### PR DESCRIPTION
**Pull request by Angelrose19**
**What did this PR accomplish?**

- Add S1-S2/2019 Scheme EST120 Question Papers ( files moved to assets)
- Add S1-S2/2019 Scheme HUN102 Question Bank

Thank you for your contribution!

### CODE REVIEW

**Review by rejahrehim — APPROVED** [review]

**Comment by rejahrehim** [comment]
@Angelrose19  Resolve conflicts

**Comment by CLiz17** [comment]
@Angelrose19 grant me the access to edit if you are facing difficulty

**Comment by rejahrehim** [comment]
Please resolve the conflicts!

**Review by gautamkrishnar — CHANGES_REQUESTED** [review]
Please remove space from all folder names. eg: `src/WikiSyllabus/KTU/2019_Scheme/S1-S2/EST102 /assets/c-if.png`

**Pull request closed without merging**
